Aut-13906 roll deallocation
spotinst/spotinst-plugin pull request #43
Opened 2023-09-06 09:58 UTC by sitay93

2023-09-14 08:48 UTC, zivmessing requested changes

2023-09-14 08:48 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +            BaseStatefulInstance statefulInstance   = getStatefulInstance(instanceId);
checj if null and write error to log that the group is stateful but the instance id {} doesnt found

2023-09-14 08:48 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +            if(statefulInstance != null && StringUtils.isNotEmpty(statefulInstance.getId())) {
remove  && StringUtils.isNotEmpty(statefulInstance.getId())

2023-09-14 09:31 UTC, zivmessing requested changes

2023-09-14 09:31 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +    protected Boolean checkIsStateful(){
and rename to checkIsStatefulGroup

2023-09-14 09:31 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +
bool isSucceeded = isStateful!=null or use blResponse (better)

2023-09-14 09:31 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +        return BooleanUtils.isTrue(isStateful);
put it boolean instead if boolean

2023-09-14 09:31 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +    private   Boolean                           isStateful;
change to boolean and initialize as false

2023-09-14 09:31 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/AwsSpotinstCloud.java
> +            statefulInstances = new LinkedList<>();
remove that line

2023-09-14 09:31 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/AwsSpotinstCloud.java
> +        Map<String, AwsStatefulInstance> ssiByInstanceId = new HashMap<>();
put that 3 lines in the if statement

2023-09-14 09:31 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/AwsSpotinstCloud.java
> +                retVal = statefulInstance != null && StringUtils.isNotEmpty(statefulInstance.getId()) &&
remove StringUtils.isNotEmpty(statefulInstance.getId()

2023-09-14 09:31 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/common/stateful/StatefulInstance.java
> +public class StatefulInstance {
done

2023-09-14 09:32 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +            if(statefulInstance != null && StringUtils.isNotEmpty(statefulInstance.getId())) {
done

2023-09-14 09:33 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +    protected Boolean checkIsStateful(){
done

2023-09-14 09:41 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +
done

2023-09-14 09:41 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +        return BooleanUtils.isTrue(isStateful);
done

2023-09-14 09:41 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/cloud/BaseSpotinstCloud.java
> +    private   Boolean                           isStateful;
done

2023-09-14 09:41 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/cloud/AwsSpotinstCloud.java
> +            statefulInstances = new LinkedList<>();
done

2023-09-14 09:42 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/cloud/AwsSpotinstCloud.java
> +        Map<String, AwsStatefulInstance> ssiByInstanceId = new HashMap<>();
done

2023-09-14 09:42 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/cloud/AwsSpotinstCloud.java
> +                retVal = statefulInstance != null && StringUtils.isNotEmpty(statefulInstance.getId()) &&
done

2023-09-14 14:50 UTC, zivmessing requested changes

2023-09-14 14:50 UTC, zivmessing commented on src/main/java/hudson/plugins/spotinst/cloud/AwsSpotinstCloud.java
> +            statefulInstances.forEach(ssi -> ssiByInstanceId.put(ssi.getInstanceId(), ssi));
use toMap just run and test

2023-09-20 07:35 UTC, sitay93 commented on src/main/java/hudson/plugins/spotinst/cloud/AwsSpotinstCloud.java
> +            statefulInstances.forEach(ssi -> ssiByInstanceId.put(ssi.getInstanceId(), ssi));
done

2023-09-20 07:49 UTC, zivmessing submitted a review, later dismissed

2023-09-21 10:12 UTC, adivos approved these changes

2023-09-21 10:13 UTC, merged